= How to get printed assembly code running by JVM?

:icons: font

icon:bookmark[] https://jpbempel.github.io/2012/10/16/how-to-print-disassembly-from-JIT-code.html, +
                https://github.com/vjuranek/code-snippets/tree/master/java/jhm, +
                https://wiki.openjdk.java.net/display/HotSpot/PrintAssembly

icon:tags[] java, assembly.code, jvm

== Main idea

Problem::   How to find what is the assembly code generated by JIT from the Java bytecode?
Solution::  Ask the JVM to print the used assembly code with arguments `-XX:+UnlockDiagnosticVMOptions -XX:+PrintAssembly`.
Benefit::   Having the idea what happens with Java code when running in real on HW.

== Details

=== How to print the assembly code?

There is need of having `hsdis-amd64.dll`/`linux-libhsdis-amd64.so` installed at the JVM
and then use the options `-XX:+UnlockDiagnosticVMOptions -XX:+PrintAssembly`
to get printed the assembly code.

The `linux-hsdis-amd64` library could be(?) in Ubuntu repositories
but the most probably it needs to be built manually.

[source,bash]
----
wget -O hsdis.tar.gz http://hg.openjdk.java.net/jdk/jdk/archive/bdc20ee1a68d.tar.gz/src/utils/hsdis/
tar -zvxf hsdis.tar.gz
cd jdk-bdc20ee1a68d/src/utils/hsdis/

wget https://ftp.gnu.org/gnu/binutils/binutils-2.35.tar.xz
tar -Jvxf binutils-2.35.tar.xz
export BINUTILS=binutils-2.35
make all64
sudo cp build/linux-amd64/hsdis-amd64.so $JAVA_HOME/jre/lib/amd64/
java -XX:+UnlockDiagnosticVMOptions -XX:+PrintAssembly -XX:PrintAssemblyOptions=intel -version
----

NOTE: using `-XX:+PrintAssembly` will print the assembly instruction of AT&T.
      The `-XX:PrintAssemblyOptions=intel` makes to get the x86 assembly code being printed.


=== How to read assembly?

You need to understand assembly basics.
Nice introduction course is at youtube https://www.youtube.com/watch?v=wLXIWKUWpSs
(Davy Wybiral, Intro to x86 Assembly Language) with 6 parts.

The basic guide with instruction could be found at
http://www.cs.virginia.edu/~evans/cs216/guides/x86.html

And blog post about reading Java `PrintAssembly` code is here
http://www.cs.virginia.edu/~evans/cs216/guides/x86.html
